name: Spring Boot CI
on:
  push:
    branches: [ main ]

jobs:
  soos_dast:
    name: SOOS DAST
    runs-on: ubuntu-latest
    steps:
      - name: Run SOOS DAST
        uses: soos-io/soos-dast-github-action@v2
        with:
          client_id: necqtvcff
          api_key: NTFiMDRiMWMtNmVkMy00ZTU1LThjYWUtODM0NzQyZjk3MjYz
          project_name: "demo"
          scan_mode: "baseline"
          api_url: "https://api.soos.io/api/"
          target_url: "https://www.example.com/"
 
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build project with Maven
        run: mvn -B clean install 

      - name: Test project with Maven 
        run: mvn test

      - name: Collect code coverage 
        uses: codecov/codecov-action@v3 

        

    
        
